# Generated by Django 4.2.1 on 2023-06-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('disp', models.TextField(max_length=150)),
                ('fees', models.IntegerField()),
            ],
        ),
    ]
